- name: Install apache install Centos
  yum: name={{ redhat_apache }} state=latest
  when: "ansible_os_family == 'RedHat'" 
- shell: service httpd status
  register: result
  until: result.stdout.find("*running") != -1
  retries: 5
  delay: 5
- debug: var=result
#- debug: Need to install telnet
#  when: "ansible_os_family == 'RedHat'"
#  notify: InstallTelnet
