- name: Install apache install Centos
  yum: name={{ redhat_apache }} state=latest
  when: "ansible_os_family == 'RedHat'" 
- name: wait for the service
  wait_for:
    port: 80
    state: started
#- debug: Need to install telnet
#  when: "ansible_os_family == 'RedHat'"
#  notify: InstallTelnet
