--- # Playbook for giving var from command line
- hosts: localhost
  remote_user: '{{ user }}'
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: capture output of id command
      command: id -un
      become_user: '{{ user }}'
      register: login
    - debug: var=login
