--- # My First YAML Playbook for Ansible
- hosts: all
  user: henry
  become: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1b
  tasks:
    - name: Remove all test packages
      apt: name=apache2 state=removed
    - name: Remove all test packages
      apt:  name=lynx state=removed
    - name: Remove all test packages
      apt: name=telnet state=removed
